### ISSUE TITLE
badger的风格问题

### ISSUE THREAD

**Issue by Yukayo** [wahyd4/badger-issues#622]
想问一下badger的style可以自由设置吗，比如从现在的flat-square变成flat

**Comment by wahyd4** [comment]
Unfortunately there is no plan to implement that feature at this moment.

**Comment by Yukayo** [comment]
Ok, thank you for your reply! Hope you can consider adding this function in the future^^

**Comment by wahyd4** [comment]
No worries, do you have any example images for me to reference?

**Comment by Yukayo** [comment]
Yes, for example, from this website https://shields.io/badges, I can generate some badges. If I choose the style as flat-square, it's similar to the current Badger's style. 
![image](https://github.com/user-attachments/assets/da61cbde-9c0d-4cba-bb64-aba49f4640ee)
If I choose the style as flat, the example as follows
![image](https://github.com/user-attachments/assets/5d073a08-c76a-4447-bb0e-16cf0d330956)
It seems the flat style is also popular with some Github pages, so hope you can consider this function. Thanks^^
